import Head from 'next/head';
import styles from '../styles/Home.module.css';
import HeadingButtons from '../components/HeadingButtons';
import OngoingLoans from '../components/OngoingLoans';
import LoanHistoryCard from '../components/LoanHistoryCard';
import WidgetCard from '../components/UI/WidgetCard';
import Widgets from '../components/Widgets';

import { RiWallet3Line } from 'react-icons/ri';
import { FiPercent } from 'react-icons/fi';
import { CiMoneyBill } from 'react-icons/ci';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Microsoft Team Mock Up</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className="container">
					<div className="heading">
						<p className="title">Loans</p>
						<HeadingButtons />
					</div>
					<div className="sub-heading">
						<span className="sub-heading_desc">Next payment</span>
						<span className="sub-heading_date">30 Mar, 2022</span>
					</div>
				</div>

				<div className="widgets">
					<div className="widget-1">
						<WidgetCard>
							<Widgets
								icon={<RiWallet3Line />}
								title="Total loans amount"
								amount="150,000.00"
								className="cover"
								widgetIcon="widget-icon"
							/>
						</WidgetCard>
					</div>
					<div className="widget-2">
						<WidgetCard>
							<div className="cover-2">
								<Widgets
									icon={<FiPercent />}
									title="Total paid amount"
									amount="15,000.00"
									className="cover-2"
									light={true}
									widgetIcon="widget-icon_2"
								/>
							</div>
						</WidgetCard>
					</div>
					<div className="widget-3">
						<WidgetCard>
							<div className="cover-3">
								<Widgets
									icon={<CiMoneyBill />}
									title="Loan Balance"
									amount="135,000.00"
									className="cover-3"
									light={true}
									widgetIcon="widget-icon_3"
								/>
							</div>
						</WidgetCard>
					</div>
				</div>
				<div
					style={{
						display: 'flex',
						justifyContent: 'center',
						gap: '6px',
						marginTop: '24px',
					}}
				>
					<div className="dots-active"></div>
					<div className="dots"></div>
					<div className="dots"></div>
				</div>

				<div className="loan-details">
					<div className="loan-history">
						<h4>Loan History</h4>
						<div className="loan-history_cards">
							<div className="loan-history_card">
								<LoanHistoryCard
									balance="2,000,000.00"
									month="6"
									year="2022"
									status="Ongoing"
								/>
							</div>
							<div className="loan-history_card-2">
								<LoanHistoryCard
									balance="5,000,000.00"
									month="12"
									year="2021"
									status="Approved"
									approved={true}
								/>
							</div>
						</div>
					</div>

					<div className="repayment-schedule">
						<h4>Repayment schedule</h4>
						<p className="repayment_subtext">
							Showing schedule for ongoing loan
						</p>
						<ul className="loans">
							<OngoingLoans month="Jan" />
							<OngoingLoans month="Feb" />
							<OngoingLoans month="Mar" />
							<OngoingLoans month="Apr" />
							<OngoingLoans month="May" />
							<OngoingLoans month="Jun" />
							<OngoingLoans month="Jul" />
							<OngoingLoans month="Aug" />
							<OngoingLoans month="Sep" />
							<OngoingLoans month="Oct" />
							<OngoingLoans month="Nov" />
							<OngoingLoans month="Dec" />
						</ul>
					</div>
				</div>
			</main>
		</div>
	);
}
