import Head from 'next/head';
import styles from '../styles/Home.module.css';
import HeadingButtons from '../components/HeadingButtons';
import LoanHistoryCard from '../components/UI/LoanHistoryCard';
import WidgetCard from '../components/UI/WidgetCard';
import Widgets from '../components/Widgets';

import { RiWallet3Line } from 'react-icons/ri';
import { FiPercent } from 'react-icons/fi';
import { CiMoneyBill } from 'react-icons/ci';
import Repayment from '../components/Repayment';
import LoanHistory from '../components/LoanHistory';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Microsoft Team Mock Up</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className="container">
					<div className="heading">
						<p className="title">Loans</p>
						<HeadingButtons />
					</div>
					<div className="sub-heading">
						<span className="sub-heading_desc">Next payment</span>
						<span className="sub-heading_date">30 Mar, 2022</span>
					</div>
				</div>

				<div className="widgets">
					<div className="widget-1">
						<WidgetCard>
							<Widgets
								icon={<RiWallet3Line />}
								title="Total loans amount"
								amount="150,000.00"
								className="cover"
								widgetIcon="widget-icon"
							/>
						</WidgetCard>
					</div>
					<div className="widget-2">
						<WidgetCard>
							<div className="cover-2">
								<Widgets
									icon={<FiPercent />}
									title="Total paid amount"
									amount="15,000.00"
									className="cover-2"
									light={true}
									widgetIcon="widget-icon_2"
								/>
							</div>
						</WidgetCard>
					</div>
					<div className="widget-3">
						<WidgetCard>
							<div className="cover-3">
								<Widgets
									icon={<CiMoneyBill />}
									title="Loan Balance"
									amount="135,000.00"
									className="cover-3"
									light={true}
									widgetIcon="widget-icon_3"
								/>
							</div>
						</WidgetCard>
					</div>
				</div>
				<div
					style={{
						display: 'flex',
						justifyContent: 'center',
						gap: '6px',
						marginTop: '24px',
					}}
				>
					<div className="dots-active"></div>
					<div className="dots"></div>
					<div className="dots"></div>
				</div>

				<div className="loan-details">
					<LoanHistory />
					<Repayment />
				</div>
			</main>
		</div>
	);
}
